#Executable
EXECUTABLE=HelloWorld

#Sources
SOURCES=HelloWorld.m \
	ObjGTK/OGTKAboutDialog.m \
	ObjGTK/OGTKAccelGroup.m \
	ObjGTK/OGTKAccelLabel.m \
	ObjGTK/OGTKAccelMap.m \
	ObjGTK/OGTKAccessible.m \
	ObjGTK/OGTKActionBar.m \
	ObjGTK/OGTKActionGroup.m \
	ObjGTK/OGTKAction.m \
	ObjGTK/OGTKAdjustment.m \
	ObjGTK/OGTKAlignment.m \
	ObjGTK/OGTKAppChooserButton.m \
	ObjGTK/OGTKAppChooserDialog.m \
	ObjGTK/OGTKAppChooserWidget.m \
	ObjGTK/OGTKApplication.m \
	ObjGTK/OGTKApplicationWindow.m \
	ObjGTK/OGTKArrowAccessible.m \
	ObjGTK/OGTKArrow.m \
	ObjGTK/OGTKAspectFrame.m \
	ObjGTK/OGTKAssistant.m \
	ObjGTK/OGTKBaseBuilder.m \
	ObjGTK/OGTKBin.m \
	ObjGTK/OGTKBooleanCellAccessible.m \
	ObjGTK/OGTKBox.m \
	ObjGTK/OGTKBuilder.m \
	ObjGTK/OGTKButtonAccessible.m \
	ObjGTK/OGTKButtonBox.m \
	ObjGTK/OGTKButton.m \
	ObjGTK/OGTKCalendar.m \
	ObjGTK/OGTKCallbackData.m \
	ObjGTK/OGTKCellAccessible.m \
	ObjGTK/OGTKCellAreaBox.m \
	ObjGTK/OGTKCellAreaContext.m \
	ObjGTK/OGTKCellArea.m \
	ObjGTK/OGTKCellRendererAccel.m \
	ObjGTK/OGTKCellRendererCombo.m \
	ObjGTK/OGTKCellRenderer.m \
	ObjGTK/OGTKCellRendererPixbuf.m \
	ObjGTK/OGTKCellRendererProgress.m \
	ObjGTK/OGTKCellRendererSpin.m \
	ObjGTK/OGTKCellRendererSpinner.m \
	ObjGTK/OGTKCellRendererText.m \
	ObjGTK/OGTKCellRendererToggle.m \
	ObjGTK/OGTKCellView.m \
	ObjGTK/OGTKCheckButton.m \
	ObjGTK/OGTKCheckMenuItemAccessible.m \
	ObjGTK/OGTKCheckMenuItem.m \
	ObjGTK/OGTKClipboard.m \
	ObjGTK/OGTKColorButton.m \
	ObjGTK/OGTKColorChooserDialog.m \
	ObjGTK/OGTKColorChooserWidget.m \
	ObjGTK/OGTKColorSelectionDialog.m \
	ObjGTK/OGTKColorSelection.m \
	ObjGTK/OGTKComboBoxAccessible.m \
	ObjGTK/OGTKComboBox.m \
	ObjGTK/OGTKComboBoxText.m \
	ObjGTK/OGTKContainerAccessible.m \
	ObjGTK/OGTKContainerCellAccessible.m \
	ObjGTK/OGTKContainer.m \
	ObjGTK/OGTKContainer+OGTKAddWidget.m \
	ObjGTK/OGTKCssProvider.m \
	ObjGTK/OGTKDialog.m \
	ObjGTK/OGTKDialog+OGTKAddButton.m \
	ObjGTK/OGTKDrawingArea.m \
	ObjGTK/OGTKEntryAccessible.m \
	ObjGTK/OGTKEntryBuffer.m \
	ObjGTK/OGTKEntryCompletion.m \
	ObjGTK/OGTKEntry.m \
	ObjGTK/OGTKEventBox.m \
	ObjGTK/OGTKEventControllerKey.m \
	ObjGTK/OGTKEventController.m \
	ObjGTK/OGTKEventControllerMotion.m \
	ObjGTK/OGTKEventControllerScroll.m \
	ObjGTK/OGTKExpanderAccessible.m \
	ObjGTK/OGTKExpander.m \
	ObjGTK/OGTKFileChooserButton.m \
	ObjGTK/OGTKFileChooserDialog.m \
	ObjGTK/OGTKFileChooserDialog+OGTKButtonTextResponseDictionary.m \
	ObjGTK/OGTKFileChooserNative.m \
	ObjGTK/OGTKFileChooserWidget.m \
	ObjGTK/OGTKFileFilter.m \
	ObjGTK/OGTKFixed.m \
	ObjGTK/OGTKFlowBoxAccessible.m \
	ObjGTK/OGTKFlowBoxChildAccessible.m \
	ObjGTK/OGTKFlowBoxChild.m \
	ObjGTK/OGTKFlowBox.m \
	ObjGTK/OGTKFontButton.m \
	ObjGTK/OGTKFontChooserDialog.m \
	ObjGTK/OGTKFontChooserWidget.m \
	ObjGTK/OGTKFontSelectionDialog.m \
	ObjGTK/OGTKFontSelection.m \
	ObjGTK/OGTKFrameAccessible.m \
	ObjGTK/OGTKFrame.m \
	ObjGTK/OGTKGestureDrag.m \
	ObjGTK/OGTKGestureLongPress.m \
	ObjGTK/OGTKGesture.m \
	ObjGTK/OGTKGestureMultiPress.m \
	ObjGTK/OGTKGesturePan.m \
	ObjGTK/OGTKGestureRotate.m \
	ObjGTK/OGTKGestureSingle.m \
	ObjGTK/OGTKGestureStylus.m \
	ObjGTK/OGTKGestureSwipe.m \
	ObjGTK/OGTKGestureZoom.m \
	ObjGTK/OGTKGLArea.m \
	ObjGTK/OGTKGObjectInitializationFailedException.m \
	ObjGTK/OGTKGrid.m \
	ObjGTK/OGTKHandleBox.m \
	ObjGTK/OGTKHBox.m \
	ObjGTK/OGTKHButtonBox.m \
	ObjGTK/OGTKHeaderBar.m \
	ObjGTK/OGTKHPaned.m \
	ObjGTK/OGTKHScale.m \
	ObjGTK/OGTKHScrollbar.m \
	ObjGTK/OGTKHSeparator.m \
	ObjGTK/OGTKHSV.m \
	ObjGTK/OGTKIconFactory.m \
	ObjGTK/OGTKIconInfo.m \
	ObjGTK/OGTKIconTheme.m \
	ObjGTK/OGTKIconViewAccessible.m \
	ObjGTK/OGTKIconView.m \
	ObjGTK/OGTKImageAccessible.m \
	ObjGTK/OGTKImageCellAccessible.m \
	ObjGTK/OGTKImage.m \
	ObjGTK/OGTKImageMenuItem.m \
	ObjGTK/OGTKIMContext.m \
	ObjGTK/OGTKIMContextSimple.m \
	ObjGTK/OGTKIMMulticontext.m \
	ObjGTK/OGTKInfoBar.m \
	ObjGTK/OGTKInfoBar+OGTKAddButtonTextResponseDictionary.m \
	ObjGTK/OGTKInvisible.m \
	ObjGTK/OGTKLabelAccessible.m \
	ObjGTK/OGTKLabel.m \
	ObjGTK/OGTKLayout.m \
	ObjGTK/OGTKLevelBarAccessible.m \
	ObjGTK/OGTKLevelBar.m \
	ObjGTK/OGTKLinkButtonAccessible.m \
	ObjGTK/OGTKLinkButton.m \
	ObjGTK/OGTKListBoxAccessible.m \
	ObjGTK/OGTKListBox.m \
	ObjGTK/OGTKListBoxRowAccessible.m \
	ObjGTK/OGTKListBoxRow.m \
	ObjGTK/OGTKListStore.m \
	ObjGTK/OGTKLockButtonAccessible.m \
	ObjGTK/OGTKLockButton.m \
	ObjGTK/OGTK.m \
	ObjGTK/OGTKMenuAccessible.m \
	ObjGTK/OGTKMenuBar.m \
	ObjGTK/OGTKMenuButtonAccessible.m \
	ObjGTK/OGTKMenuButton.m \
	ObjGTK/OGTKMenuItemAccessible.m \
	ObjGTK/OGTKMenuItem.m \
	ObjGTK/OGTKMenu.m \
	ObjGTK/OGTKMenuShellAccessible.m \
	ObjGTK/OGTKMenuShell.m \
	ObjGTK/OGTKMenuToolButton.m \
	ObjGTK/OGTKMessageDialog.m \
	ObjGTK/OGTKMessageDialog+OGTKWithMarkup.m \
	ObjGTK/OGTKMisc.m \
	ObjGTK/OGTKModelButton.m \
	ObjGTK/OGTKMountOperation.m \
	ObjGTK/OGTKNativeDialog.m \
	ObjGTK/OGTKNotebookAccessible.m \
	ObjGTK/OGTKNotebook.m \
	ObjGTK/OGTKNotebookPageAccessible.m \
	ObjGTK/OGTKObject.m \
	ObjGTK/OGTKOffscreenWindow.m \
	ObjGTK/OGTKOverlay.m \
	ObjGTK/OGTKPadController.m \
	ObjGTK/OGTKPageSetup.m \
	ObjGTK/OGTKPanedAccessible.m \
	ObjGTK/OGTKPaned.m \
	ObjGTK/OGTKPlacesSidebar.m \
	ObjGTK/OGTKPopoverAccessible.m \
	ObjGTK/OGTKPopover.m \
	ObjGTK/OGTKPopoverMenu.m \
	ObjGTK/OGTKPrintContext.m \
	ObjGTK/OGTKPrintOperation.m \
	ObjGTK/OGTKPrintSettings.m \
	ObjGTK/OGTKProgressBarAccessible.m \
	ObjGTK/OGTKProgressBar.m \
	ObjGTK/OGTKRadioAction.m \
	ObjGTK/OGTKRadioButtonAccessible.m \
	ObjGTK/OGTKRadioButton.m \
	ObjGTK/OGTKRadioMenuItemAccessible.m \
	ObjGTK/OGTKRadioMenuItem.m \
	ObjGTK/OGTKRadioToolButton.m \
	ObjGTK/OGTKRangeAccessible.m \
	ObjGTK/OGTKRange.m \
	ObjGTK/OGTKRcStyle.m \
	ObjGTK/OGTKRecentAction.m \
	ObjGTK/OGTKRecentChooserDialog.m \
	ObjGTK/OGTKRecentChooserDialog+OGTKButtonTextResponseDictionary.m \
	ObjGTK/OGTKRecentChooserMenu.m \
	ObjGTK/OGTKRecentChooserWidget.m \
	ObjGTK/OGTKRecentFilter.m \
	ObjGTK/OGTKRecentManager.m \
	ObjGTK/OGTKRendererCellAccessible.m \
	ObjGTK/OGTKRevealer.m \
	ObjGTK/OGTKScaleAccessible.m \
	ObjGTK/OGTKScaleButtonAccessible.m \
	ObjGTK/OGTKScaleButton.m \
	ObjGTK/OGTKScale.m \
	ObjGTK/OGTKScrollbar.m \
	ObjGTK/OGTKScrolledWindowAccessible.m \
	ObjGTK/OGTKScrolledWindow.m \
	ObjGTK/OGTKSearchBar.m \
	ObjGTK/OGTKSearchEntry.m \
	ObjGTK/OGTKSeparator.m \
	ObjGTK/OGTKSeparatorMenuItem.m \
	ObjGTK/OGTKSeparatorToolItem.m \
	ObjGTK/OGTKSettings.m \
	ObjGTK/OGTKShortcutLabel.m \
	ObjGTK/OGTKShortcutsGroup.m \
	ObjGTK/OGTKShortcutsSection.m \
	ObjGTK/OGTKShortcutsShortcut.m \
	ObjGTK/OGTKShortcutsWindow.m \
	ObjGTK/OGTKSignalConnector.m \
	ObjGTK/OGTKSignalData.m \
	ObjGTK/OGTKSizeGroup.m \
	ObjGTK/OGTKSpinButtonAccessible.m \
	ObjGTK/OGTKSpinButton.m \
	ObjGTK/OGTKSpinnerAccessible.m \
	ObjGTK/OGTKSpinner.m \
	ObjGTK/OGTKStackAccessible.m \
	ObjGTK/OGTKStack.m \
	ObjGTK/OGTKStackSidebar.m \
	ObjGTK/OGTKStackSwitcher.m \
	ObjGTK/OGTKStatusbarAccessible.m \
	ObjGTK/OGTKStatusbar.m \
	ObjGTK/OGTKStatusIcon.m \
	ObjGTK/OGTKStyleContext.m \
	ObjGTK/OGTKStyle.m \
	ObjGTK/OGTKStyleProperties.m \
	ObjGTK/OGTKSwitchAccessible.m \
	ObjGTK/OGTKSwitch.m \
	ObjGTK/OGTKTable.m \
	ObjGTK/OGTKTearoffMenuItem.m \
	ObjGTK/OGTKTextBuffer.m \
	ObjGTK/OGTKTextCellAccessible.m \
	ObjGTK/OGTKTextChildAnchor.m \
	ObjGTK/OGTKTextMark.m \
	ObjGTK/OGTKTextTag.m \
	ObjGTK/OGTKTextTagTable.m \
	ObjGTK/OGTKTextViewAccessible.m \
	ObjGTK/OGTKTextView.m \
	ObjGTK/OGTKThemingEngine.m \
	ObjGTK/OGTKToggleAction.m \
	ObjGTK/OGTKToggleButtonAccessible.m \
	ObjGTK/OGTKToggleButton.m \
	ObjGTK/OGTKToggleToolButton.m \
	ObjGTK/OGTKToolbar.m \
	ObjGTK/OGTKToolButton.m \
	ObjGTK/OGTKToolItemGroup.m \
	ObjGTK/OGTKToolItem.m \
	ObjGTK/OGTKToolPalette.m \
	ObjGTK/OGTKTooltip.m \
	ObjGTK/OGTKToplevelAccessible.m \
	ObjGTK/OGTKTreeModelFilter.m \
	ObjGTK/OGTKTreeModelSort.m \
	ObjGTK/OGTKTreeSelection.m \
	ObjGTK/OGTKTreeStore.m \
	ObjGTK/OGTKTreeViewAccessible.m \
	ObjGTK/OGTKTreeViewColumn.m \
	ObjGTK/OGTKTreeView.m \
	ObjGTK/OGTKTypeWrapper.m \
	ObjGTK/OGTKUIManager.m \
	ObjGTK/OGTKVBox.m \
	ObjGTK/OGTKVButtonBox.m \
	ObjGTK/OGTKViewport.m \
	ObjGTK/OGTKVolumeButton.m \
	ObjGTK/OGTKVPaned.m \
	ObjGTK/OGTKVScale.m \
	ObjGTK/OGTKVScrollbar.m \
	ObjGTK/OGTKVSeparator.m \
	ObjGTK/OGTKWidgetAccessible.m \
	ObjGTK/OGTKWidget.m \
	ObjGTK/OGTKWindowAccessible.m \
	ObjGTK/OGTKWindowGroup.m \
	ObjGTK/OGTKWindow.m

#Objects
OBJECTS=$(SOURCES:.m=.o)

#compiler
CC=clang

#CFLAGS
CFLAGS=`objfw-config --cppflags` `pkg-config --cflags gtk+-3.0` -g -O0 -c -Wno-deprecated-declarations -Wno-deprecated

#Objective-c specific flags
OBJCFLAGS=`objfw-config --objcflags`

#Objective-c specific flags
MACOBJCFLAGS=$(OBJCFLAGS)

#GTK dependencies
GTKDEPS=`pkg-config --libs gtk+-3.0`

#Common flags
COMMONFLAGS=$(CFLAGS) $(OBJCFLAGS)

LIBS=`objfw-config --rpath --libs` $(GTKDEPS)

#Targets

#Linux Target
linux: all

#Mac Target
mac: COMMONFLAGS=$(MACOBJCFLAGS) $(GTKDEPS)
mac: all

#Windows Target
windows: all

#All Target
all: $(SOURCES) $(EXECUTABLE)

$(EXECUTABLE): $(OBJECTS)
	$(CC) $(OBJECTS) $(LIBS) -o $@

%.o: %.m
	$(CC) $(COMMONFLAGS) $< -o $@

clean: 
	rm -rf *.o *.d $(EXECUTABLE)
	rm -rf ObjGTK/*.o ObjGTK/*.d $(EXECUTABLE)
