SRCS = OFDictionary+OGTKJsonDictionaryOfFile.m \
	OGTKClass.m \
	OGTKClassWriter.m \
	OGTKLibraryWriter.m \
	OGTKLibrary.m \
	OGTKMapper.m \
	OGTKMethod.m \
	OGTKParameter.m \
	OGTKTemplate.m \
	OGTKUtil.m

STATIC_LIB_NOINST = lib.a

include ../../buildsys.mk