SRCS = OGTKDataProcessingNotImplementedException.m \
	OGTKIncorrectConfigException.m \
	OGTKNoGIRAPIException.m \
	OGTKNoGIRDictException.m \
	OGTKReceivedNilExpectedStringException.m

STATIC_LIB_NOINST = lib.a

include ../../buildsys.mk
